stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: python:3.6-alpine3.12
  before_script:
     - pip install -r requirements.txt -r requirements-test.txt
  script: 
    - python3 -m unittest discover -s tests/ 
    - coverage run -m unittest discover -s tests/ 
    - coverage report --include crawler/crawler.py

build:
  stage: build
  image: docker:stable
  services:
    - docker-dind
  
  

  
