apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: search-engine
    component: crawler
    release: {{ .Release.Name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: search-engine
      component: crawler
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler
      labels:
        app: search-engine
        component: crawler
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: crawler
        env:
          - name: MONGO
            value: mongodb
          - name: MONGO_PORT
            value: '27017'
